In [1]:
import tensorflow as tf
import numpy as np

In [2]:
inputs = tf.placeholder(tf.float32,[None,2],name='input')
labels = tf.placeholder(tf.float32,[None,1],name='label')
#Hidden Layer 1
W = tf.Variable(tf.truncated_normal([2,2],stddev=0.1,name='Weights'))
b = tf.Variable(tf.constant(0.1,shape=[2]),name='biases')
pre_act = tf.matmul(inputs,W) + b
output = tf.nn.relu(pre_act,name='activation')
#Output Layer
Wo = tf.Variable(tf.truncated_normal([2,1],stddev=0.1,name='Weights_out'))
bo = tf.Variable(tf.constant(0.1,shape=[1]),name='biases_out')
pre_act_o = tf.matmul(output,Wo) + bo
out_y = tf.nn.relu(pre_act_o,name='act_y')

loss = tf.reduce_mean((out_y-labels)**2)
train_step = tf.train.AdamOptimizer(1e-4).minimize(loss)

In [3]:
sess = tf.InteractiveSession()
tf.initialize_all_variables().run()

In [4]:
x=[[0,0],[0,1],[1,0],[1,1]]
y=[[0],[1],[1],[0]]
X=np.array(x).astype('int16')
Y=np.array(y).astype('int16')

In [ ]:
W.eval()

In [ ]:
Wo.eval()

In [5]:
for i in range(10000):
    sess.run(train_step,feed_dict={inputs:X, labels:Y})
    if i%100 == 0:
        l2 = loss.eval(feed_dict={inputs:X,labels:Y})
        print('Training #%d loss: %.2f'%(i,l2))

Training #0 loss: 0.42
Training #100 loss: 0.41
Training #200 loss: 0.40
Training #300 loss: 0.38
Training #400 loss: 0.38
Training #500 loss: 0.37
Training #600 loss: 0.36
Training #700 loss: 0.35
Training #800 loss: 0.34
Training #900 loss: 0.33
Training #1000 loss: 0.33
Training #1100 loss: 0.32
Training #1200 loss: 0.31
Training #1300 loss: 0.31
Training #1400 loss: 0.30
Training #1500 loss: 0.29
Training #1600 loss: 0.29
Training #1700 loss: 0.28
Training #1800 loss: 0.28
Training #1900 loss: 0.27
Training #2000 loss: 0.27
Training #2100 loss: 0.26
Training #2200 loss: 0.26
Training #2300 loss: 0.25
Training #2400 loss: 0.25
Training #2500 loss: 0.24
Training #2600 loss: 0.24
Training #2700 loss: 0.23
Training #2800 loss: 0.23
Training #2900 loss: 0.22
Training #3000 loss: 0.22
Training #3100 loss: 0.21
Training #3200 loss: 0.21
Training #3300 loss: 0.20
Training #3400 loss: 0.20
Training #3500 loss: 0.19
Training #3600 loss: 0.19
Training #3700 loss: 0.18
Training #3800 loss: 0.1

In [ ]:
T = 1000 #训练 10000 epoch
for i in range(T):
    for j in range(X.shape[0]):
        sess.run(train_step,feed_dict={inputs:X[j], labels:Y[j]})
    if i%100 == 0:
        l2 = loss.eval(feed_dict={inputs:X,labels:Y})
        print('Training #%d loss: %.2f'%(i,l2))

In [6]:
W.eval()

array([[ 0.90999919, -0.85135514],
       [-0.91000968,  0.851331  ]], dtype=float32)

In [7]:
Wo.eval()

array([[ 0.87849224],
       [ 0.9963671 ]], dtype=float32)

In [8]:
loss.eval(feed_dict={inputs:X,labels:Y})

0.0080968821

In [10]:
pY = sess.run(out_y,feed_dict={inputs:X})
pY

array([[ 0.09428272],
       [ 0.94248009],
       [ 0.89369607],
       [ 0.09428272]], dtype=float32)